name: goat_flutter_challenge
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^4.2.7

  ui_book:
    path: module/ui/ui_book

  service_locator:
    path: module/library/service_locator

  network_client:
    path: module/library/network_client

  domain_book:
    path: module/domain/domain_book

  data_book:
    path: module/data/data_book

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  localization:
    path: module/library/localization

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

