name: ui_book
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  localization:
    path: ../../library/localization

  base_component:
    path: ../../library/base_component

  base_asset:
    path: ../../library/base_asset

  cubit_util:
    path: ../../library/cubit_util

  go_router: ^4.2.7

  # url: https://pub.dev/packages/shimmer
  # desc: A package provides an easy way to add shimmer effect
  shimmer: 2.0.0

  # url: https://pub.dev/packages/flutter_bloc
  # desc: StateManagement library for cubit and bloc
  flutter_bloc: 8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
