name: ui_book
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  localization:
    path: ../../library/localization

  base_component:
    path: ../../library/base_component

  base_asset:
    path: ../../library/base_asset

  cubit_util:
    path: ../../library/cubit_util

  result_util:
    path: ../../library/result_util

  network_client:
    path: ../../library/network_client

  domain_book:
    path: ../../domain/domain_book

  entity_book:
    path: ../../entity/entity_book

  go_router: ^4.2.7

  url_launcher: 6.1.5

  async: 2.8.2

  # for downloading
  flowder:
    git:
      url: https://github.com/mapacheverdugo/flowder
      ref: b53316a53b56deec01a25be8cb8c73e2b8da2947

  path_provider: 2.0.11
  percent_indicator: 4.2.2
  open_file: 3.2.1

  # url: https://pub.dev/packages/shimmer
  # desc: A package provides an easy way to add shimmer effect
  shimmer: 2.0.0

  # url: https://pub.dev/packages/flutter_bloc
  # desc: StateManagement library for cubit and bloc
  flutter_bloc: 8.0.1

  # url: https://pub.dev/packages/sliver_tools
  # desc: A set of useful sliver tools that are missing from the flutter framework.
  sliver_tools: 0.2.7

  collection: 1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  fake_domain_book:
    path: ../../domain/fake_domain_book

  test_util:
    path: ../../library/test_util

# The following section is specific to Flutter packages.
flutter:
  assets:
    - asset/icon/
    - asset/image/
