// DON'T EDIT THE CODE.
// This code generated by lib localization.
import 'package:localization/localization.dart';

class BookLocaleResource extends LocaleResource {
  BookLocaleResource(String? languageCode) : super(languageCode);
  
  @override
  Map<String, Map<String, String>> get data => {
    'books': {
      'default': 'Books',
      'id': 'Buku',
      'ja': '図書',
    },
    'booksDetail': {
      'default': 'Books Detail',
      'id': 'Detail Buku',
      'ja': '書籍詳細',
    },
    'downloads': {
      'default': 'Downloads',
      'id': 'Unduh',
      'ja': 'ダウンロード',
    },
    'readHere': {
      'default': 'Read Here',
      'id': 'Baca disini',
      'ja': 'ここを読む',
    },
    'authors': {
      'default': 'Authors: %s',
      'id': 'Pengarang: %s',
      'ja': '著者: %s',
    },
    'search': {
      'default': 'Search',
      'id': 'Cari',
      'ja': 'サーチ',
    },
  };
}
