// DON'T EDIT THE CODE.
// This code generated by lib localization.
import 'package:localization/localization.dart';
import 'package:ui_book/src/locale/book_locale_resource.dart';

class BookLocale extends GoatLocale {
  BookLocale([String? languageCode]) : super(languageCode);
  
  String get books {
    return resource.get('books');
  }
  
  String get booksDetail {
    return resource.get('booksDetail');
  }
  
  String get downloads {
    return resource.get('downloads');
  }
  
  String get readHere {
    return resource.get('readHere');
  }
  
  String get author {
    return resource.get('author');
  }
  
  String get title {
    return resource.get('title');
  }
  
  String get search {
    return resource.get('search');
  }
  
  String get somethingWrong {
    return resource.get('somethingWrong');
  }
  
  String get alienBlocking {
    return resource.get('alienBlocking');
  }
  
  String get retry {
    return resource.get('retry');
  }
  
  @override
  LocaleResource get resource {
    return BookLocaleResource(languageCode);
  }
}
