// DON'T EDIT THE CODE.
// This code generated by lib localization.
import 'package:localization/localization.dart';

class BookLocaleResource extends LocaleResource {
  BookLocaleResource(String? languageCode) : super(languageCode);
  
  @override
  Map<String, Map<String, String>> get data => {
    'books': {
      'default': 'Books',
      'id': 'Buku',
      'ja': '図書',
    },
    'booksDetail': {
      'default': 'Book Details',
      'id': 'Detail Buku',
      'ja': '本の詳細',
    },
    'downloads': {
      'default': 'Downloads',
      'id': 'Unduh',
      'ja': 'ダウンロード',
    },
    'readHere': {
      'default': 'Read Here',
      'id': 'Baca disini',
      'ja': 'ここを読む',
    },
    'authors': {
      'default': 'Authors: %s',
      'id': 'Pengarang: %s',
      'ja': '著者: %s',
    },
    'search': {
      'default': 'Search',
      'id': 'Cari',
      'ja': 'サーチ',
    },
    'somethingWrong': {
      'default': 'Something went wrong..',
      'id': 'Terjadi Kesalahan..',
      'ja': '何かがうまくいかなかった',
    },
    'alienBlocking': {
      'default': 'An alien is probably blocking your signal.',
      'id': 'Alien mungkin memblokir sinyal Anda.',
      'ja': 'エイリアンがあなたの信号をブロックしている可能性があります。',
    },
    'retry': {
      'default': 'Retry',
      'id': 'Coba Lagi',
      'ja': 'リトライ',
    },
  };
}
