name: fake_entity_book
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: 2.8.2

  entity_book:
    path: ../../entity/entity_book

  nullable_util:
    path: ../../library/nullable_util

  network_client:
    path: ../../library/network_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

